/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IExecutionPermissions_EventsContract
  extends Truffle.Contract<IExecutionPermissions_EventsInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<IExecutionPermissions_EventsInstance>;
}

export interface OwnerNominated {
  name: "OwnerNominated";
  args: {
    from: string;
    to: string;
    0: string;
    1: string;
  };
}

export interface OwnershipClaimed {
  name: "OwnershipClaimed";
  args: {
    from: string;
    to: string;
    0: string;
    1: string;
  };
}

type AllEvents = OwnerNominated | OwnershipClaimed;

export interface IExecutionPermissions_EventsInstance
  extends Truffle.ContractInstance {
  methods: {};

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
