/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ExampleUsageContract } from "./ExampleUsage";
import { ExecutionPermissionsContract } from "./ExecutionPermissions";
import { IExecutionPermissions_EventsContract } from "./IExecutionPermissions_Events";
import { IExecutionPermissions_FunctionsContract } from "./IExecutionPermissions_Functions";
import { IExecutionPermissionsContract } from "./IExecutionPermissions";
import { IExecutionPermissions_VariablesContract } from "./IExecutionPermissions_Variables";
import { IOwnableContract } from "./IOwnable";
import { MigrationsContract } from "./Migrations";
import { NotOwnableContract } from "./NotOwnable";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ExampleUsage"): ExampleUsageContract;
      require(name: "ExecutionPermissions"): ExecutionPermissionsContract;
      require(
        name: "IExecutionPermissions_Events"
      ): IExecutionPermissions_EventsContract;
      require(
        name: "IExecutionPermissions_Functions"
      ): IExecutionPermissions_FunctionsContract;
      require(name: "IExecutionPermissions"): IExecutionPermissionsContract;
      require(
        name: "IExecutionPermissions_Variables"
      ): IExecutionPermissions_VariablesContract;
      require(name: "IOwnable"): IOwnableContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "NotOwnable"): NotOwnableContract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export { ExampleUsageContract, ExampleUsageInstance } from "./ExampleUsage";
export {
  ExecutionPermissionsContract,
  ExecutionPermissionsInstance,
} from "./ExecutionPermissions";
export {
  IExecutionPermissions_EventsContract,
  IExecutionPermissions_EventsInstance,
} from "./IExecutionPermissions_Events";
export {
  IExecutionPermissions_FunctionsContract,
  IExecutionPermissions_FunctionsInstance,
} from "./IExecutionPermissions_Functions";
export {
  IExecutionPermissionsContract,
  IExecutionPermissionsInstance,
} from "./IExecutionPermissions";
export {
  IExecutionPermissions_VariablesContract,
  IExecutionPermissions_VariablesInstance,
} from "./IExecutionPermissions_Variables";
export { IOwnableContract, IOwnableInstance } from "./IOwnable";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { NotOwnableContract, NotOwnableInstance } from "./NotOwnable";
export { OwnableContract, OwnableInstance } from "./Ownable";
